# Site settings
title: ING
email: t@okzk.org
description: ""
baseurl: ""
url: "http://okzk.org"
category_dir: ''
twitter_username: tokzk
github_username:  tokzk

# Build settings
markdown: kramdown
permalink: pretty
